### PR TITLE
Added ordered signature and some documentation

### PR DESCRIPTION
**Pull request by BojanKogoj**
According to documentation response signature is generated in predefined sequence, which is what I've done. Also added some basic documentation.

### CODE REVIEW

**Comment by BojanKogoj** [comment]
@antonioperic you were right, the method I added does not work for failure response, since there is a different response.

**Comment by antonioperic** [comment]
@BojanKogoj can you do another PR?

**Comment by BojanKogoj** [comment]
And add method for failure? I could

**Comment by antonioperic** [comment]
That or remove method. Whatever you prefer

**Pull request merged**
